name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main # This should be the name of your default branch (usually 'main' or 'master')

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your Node.js version, e.g., 20
          cache: npm # Or yarn, pnpm

      - name: Install dependencies
        run: npm install # Or yarn install, pnpm install

      - name: Build website
        run: npm run build # Or yarn build, pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'